linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - golint
    - govet
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unused
    - whitespace
issues:
  exclude:
    - "not declared by package utf8"
    - "unicode/utf8/utf8.go"
